spring:
  profiles:
    active: default
  liquibase:
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    change-log: classpath:db/changelog/db-changelog-master.xml
    contexts: initialise,standard
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    datasource:
      driverClassName: org.h2.Driver


  h2:
    console:
      path: /h2-console
      url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
      enabled: true
      username: sa
      password: